### ISSUE TITLE
INSERT query wont work, makes php page blank

### ISSUE THREAD

**Issue by yelnyafacee** [colshrapnel/thebestpdowrapper#1]
I using SQL insert query:

INSERT INTO fc_users (fc_users.user_name, fc_users.user_password, fc_users.user_email, fc_users.user_facebook, fc_users.user_profile_image_url) VALUES (?, ?, ?, ?, ?)

with 

DB::prepare($normal_login_register_request)->execute([$username, $hashed_password, $email, 1, $facebookUserImgURL_DB])->fetchColumn();

no matter what fetch method I used my php page goes blank

**Comment by yelnyafacee** [comment]
it successfully INSERT but it cause PHP blank page error

**Comment by colshrapnel** [comment]
You aren't supppsed to fetch anything from the INSERT query. Just get rid of fetchColumn call.

A blank page you see is caused by the error reporting settings. If it's a dev server, just set display_errors on.

**Comment by yelnyafacee** [comment]
even with fetchColumn call removed:

DB::prepare($sql)->execute([$username,$hashed_password,$email,1,$facebookUserImgURL_DB]);

it still give a blank page, is there anyway to prevent this?

**Comment by yehximin** [comment]
I tried putting "error_reporting(E_ALL);" on top of the PHP file

but still no error is generated with:

DB::prepare($sql)->execute([$username,$hashed_password,$email,1,$facebookUserImgURL_DB]);

**Comment by yelnyafacee** [comment]
Thank you, I am able to view the errors now,

would like to know how to deal with INSERT errors, like row already exist etc and success

where should I add  the code so it will return the error or response to the variable container?

**Comment by colshrapnel** [comment]
In general you don't have to add any code. Just show success message. 

If you want to show some specific error page instead of blank screen - set up your web-server

**Comment by yelnyafacee** [comment]
I have modified "myPDOStatement" class to:

class myPDOStatement extends PDOStatement
{
    function execute($data = array())
    {

```
    try {

        parent::execute($data);

        if(is_a($this, 'myPDOStatement')){

            return "success";

        } else {

            return var_dump($this);

        }


    }
    catch (PDOException $e) {

        // RETURN ERROR MESSAGE
        return $e->getMessage();


    }


}
```

}

but not sure if the " if(is_a($this, 'myPDOStatement')){" will make sure that this is indeed a "success", if anything go wrong in UPDATE/INSERT/SELECT/COUNT etc,

will ti all goto "catch (PDOException $e) {"?

**Comment by colshrapnel** [comment]
It makes absolutely no sense. There is no point in returning errors or some random words.
Read this: http://phpdelusions.net/pdo#errors

**Comment by yelnyafacee** [comment]
but I really need the return results, because depending on the returned result ( string in my case ), I will run other codes to return different json response string back to the android phone app
