### ISSUE TITLE
cant prepare mysql statement with LIKE % wildcard character

### ISSUE THREAD

**Issue by yelnyafacee** [colshrapnel/thebestpdowrapper#6]
hi,

I tried:   $request = SELECT \* FROM table WHERE table.res_name LIKE '?%'

and

$result = DB::prepare($request)->execute([$search_keyword])->fetchAll();

it wont work as well as '$search_keyword%' etc

but if: $request = SELECT \* FROM table WHERE table.res_name LIKE '$search_keyword%'

and

$result = DB::prepare($request)->execute()->fetchAll();

it is ok, is there anyway to make the wildcard char work?

**Comment by colshrapnel** [comment]
That's very simple. You just have to bind the whole string literal, not a part of it:

```
$request = "SELECT * FROM table WHERE table.res_name LIKE ?";
$result = DB::prepare($request)->execute(["$search_keyword%"])->fetchAll();
```
